apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: event-app
  template:
    metadata:
      labels:
        app: event-app
    spec:
      containers:
      - name: event-app
        image: event-app:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: event-app-service
spec:
  selector:
    app: event-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort